### ISSUE TITLE
Add sushiswap to polygon honeyswap aggregator

### ISSUE THREAD

**Issue by Monstrosity1** [1Hive/honeyswap#105]
As a Honeyswap trader, I would like my swaps on Honeyswap Polygon to route through the most cost effective swapping pairs, so that I can get the best value for my trade. 

GIVEN I am on Honeyswap Polygon
WHEN I swap any pair
AND the best price is available from Sushiswap
THEN my swap routes through Sushiswap

GIVEN I am on Honeyswap Polygon
WHEN I am previewing my swap
THEN I see the rate available from Sushiswap in the possible options

GIVEN I am on Honeyswap Polygon
WHEN I am previewing my swap
THEN I can choose to manually route my swap through Sushiswap
________
need more than just quickswap and honeyswap otherwise people may not see much use for the platform

**Comment by Monstrosity1** [comment]
## User story

As a [trader/swapper], I would like to [use honeyswap], so that I [swap and find the best route]

## Acceptance Criteria

GIVEN 
WHEN user makes a swap between usdc to sushi their is significant slippage because best route is on sushiswap and honeyswap only uses quickswap and honeyswap.
THEN usdc to sushi should also look at sushiswap

## Design
* 

## Notes
* need more than just quickswap and honeyswap otherwise people may not see much use for the platform

**Comment by hernandoagf** [comment]
Task completed
