### ISSUE TITLE
Airdrop Contract/Discussion

### ISSUE THREAD

**Issue by Blazarius120** [1Hive/honeyswap#11]

**Comment by Blazarius120** [comment]
1) Merkle airdrop with claim function

**Comment by Philogy** [comment]
Will also require some sort of api to retrieve the merkle proof for individual addresses.

**Comment by Philogy** [comment]
Since the fees on xdai are so low we could just airdrop to everyone automatically. Also what kind of Airdrop are we discussing, are you planning to airdrop the HSF token?

**Comment by Blazarius120** [comment]
Questions that need to be answered: Determine the list of tokens that we will need to incentivize, their allocation %'s, what percent of tokens should be airdropped from the total supply & vesting period?

**Comment by Philogy** [comment]
General consensus seems to be that an airdrop of 5-10% to old liquidity providers is a good idea. I think a Merkle tree based airdrop contract is not worth the additional backend and smart contract effort considering that xDai fees are so low that the airdrop can directly be executed.

__Questions that remain to be answered__:
- [ ] how much to airdrop, 5-10% ?
- [ ] how to take the snapshot ?
- [ ] when to take the snapshot ?
- [ ] should the snapshot be announced ?
- [ ] should airdropped tokens be vested?

**Comment by Blazarius120** [comment]
-how much to airdrop? 5%
 -should airdropped tokens be vested? 10% upfront, and the rest is vested over the period in time (1 year)
-when to take the snapshot ? taken from subgraph over the pools time period to determine averaged staked
-Linear release schedule for rewards

**Comment by Philogy** [comment]
Scripts for creating snapshot are down, just need to agree on the pair and weights now. No backend will be required to service the airdrop receivers.
