### ISSUE TITLE
Sustainable Farming Documentation

### ISSUE THREAD

**Issue by Blazarius120** [1Hive/honeyswap#12]

**Comment by Blazarius120** [comment]
1) Document into wiki, update milestone section
2) create forum post

**Comment by Blazarius120** [comment]
https://medium.com/@honeyswap/1hive-yield-farming-e38d3ad25c92 first draft of the medium article for sustainable farming

**Comment by Philogy** [comment]
Here's a link to a file documenting the farming contracts in quite deep detail: https://hackmd.io/BFrhyOTUQ3O9REs5PuZahQ may be too technical for the general documentation, still I hope it helps!

**Comment by lkngtn** [comment]
Estimated completion by friday may 7

**Comment by ceresbzns** [comment]
Completed for xComb launch. 
Need a new ticket for pComb airdrop, launch, farms, etc.
