### ISSUE TITLE
wallet calculations for LP positions look broken

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#129]
**Describe the bug**
LP calculations showing in the wallet seem incorrect. USDC-ETH positions on Polygon show as 0.00 balance with an astronomical price. Values are showing correctly. 

**To Reproduce**
1. Go to 1hive.io
2. Connect wallet containing a USDC-ETH (polygon) or USDC-DAI (xdai) LP position
3. Scroll down to Balance + Price in the table
4. See 0.00 balance with Price in $millions

**Expected behavior**
This is inconsistent. Other LPs (such as DAI-ETH on Polygon) show positive Balances with Price in $10s or $100s. 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/60b150d0aa64fc7a662399c6/1b92ad33-7849-4c61-9db1-12ea0e254354)If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Comment by pxbee** [comment]
The price is correct. It's because the LP was created with a weird ratio and it just stays that way. I'll change it so the correct LP balance will be shown. It's cut of after 2 decimal places at the moment.
