### ISSUE TITLE
Sustainable Farming Marketing Coordination

### ISSUE THREAD

**Issue by Blazarius120** [1Hive/honeyswap#13]

**Comment by Blazarius120** [comment]
1) airdrop (ex: 10% of initial tokens), snapshot after the announcement
2) farming

-choose pairs that people actually want to trade and that will bring value to 1Hive
-Proportional to the amount of LP you are providing
-NFT airdrop
-Time lock liquidity? extra rewards?

Marketing Prospects:
-HSF airdrop & farming initiatives (phase 1)
-Agave Launch (phase 1)
-Kshazu & NFT promotions (phase 1?)
-Connext bridge & liquidity aggregation (phase 2)

Marketing Initiatives:
-Exposure from Articles (Medium/Publish0x)
-Youtuber support (multiple small/medium or one large)
-Social media: forum post, twitter post, reddit, etc. (maybe promotions around the posts like $100 giveaway in HNY or something to draw interest)

Documentation:
-Media pamphlet for external parties to easily understand and create content off of
-Update to wiki (new section for farming + milestone section for phase 1 & phase 2)
-Update the landing page to add the new farming page (and remove old farming section)

**Comment by ceresbzns** [comment]
Let's revisit
