### ISSUE TITLE
Update Polygon Honeycomb wiki with addresses

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#130]
Need addresses for: 
Subgraphs
Fee Receiver Contract

https://wiki.1hive.org/projects/honeyswap/honeyswap-on-polygon

**Comment by metaverde** [comment]
https://wiki.1hive.org/projects/honeyswap/honeyswap-on-polygon
I'm not sure which addresses we need.
I'm thinking Enti nailed it?

**Comment by eenti** [comment]
Just saw this, and yeah I did get all addresses. I'll close this issue.
