### ISSUE TITLE
Farming Incentives Scope/Requirements

### ISSUE THREAD

**Issue by lkngtn** [1Hive/honeyswap#14]

**Comment by Philogy** [comment]
Ideas:
* timelocked LPs get higher yield
* allow LPs to unlock early for penalty
* allow LPs to sell their locked liquidity
* progressively increasing yield as liquidity has remained locked

**Comment by lkngtn** [comment]
Whatever we end up doing for farming rewards, I want to stick with something we feel comfortable describing as "**Simple, No BS rewards for LPs**". 

I think the key problem we are trying to solve with sustainable farming is that there is no speculative aspect to LPing, as you generally expect that more LP will arrive to offset any increases in trading volume. By introducing HSF-xDai, people who decide to LP now, will get a cut of future rewards even as the total liquidity increases (and therefore their share of the fees decreases). 

I think that providing some amplification for people who are in the farm longer would be fine, its still pretty simple "the longer you remain in the farm the greater the reward", and this would help minimize the urge for LPs to jump ship to other farms even if the current APY may be temporarily higher. If we can do this with the contract without too much extra complexity (and contract risk and effort) I think it would be worthwhile, otherwise I think we would be fine with just the most basic flow. 

One other thing we could do, which may be quite easy, is to have a portion of the rewards that users earn locked, this may be a bit easier to implement and still be pretty simple, but would have a similar effect of incentivizing LPs to be loyal to the platform, since a part of their rewards wouldn't "vest" back to them immediately. 

Regarding time locked LPs getting higher yield, unlock penalties, and LPs being able to sell their blocks of locked LPs... I think there are some interesting possibilities here, but the more I think about it the more I think its a bit of a rabbit hole to go down, and Im not sure it really aligns with the idea of "simple, no BS rewards for LPs." 

Perhaps we could set the expectation that we may iterate on farming rewards, but that the HSF-xDai token will always get at least 50% of the instances platform fees. That way if we decide that we need to introduce additional mechanism to the farming to effectively compete for liquidity we can do that without breaking any social expectation around the token.

**Comment by Philogy** [comment]
Technically a timelock based multiplier should be quite simple. For every deposit to the pool the deposited amount has to be tracked, instead of using the deposited amount 1:1 to represent the depositors share it's run through a simple formula with the lock time to calculate the actual pool share. Now each deposit just also has to keep track of the unlock time. In the withdraw method you just need an additional check to make sure that the unlock time is lower than the current block timestamp.

Other features or variations of this may be more complex to implement. If stakes are tracked individually however a ERC721 tokenization option can easily be added down the line.

**Comment by lkngtn** [comment]
> Technically a timelock based multiplier should be quite simple. For every deposit to the pool the deposited amount has to be tracked, instead of using the deposited amount 1:1 to represent the depositors share it's run through a simple formula with the lock time to calculate the actual pool share. Now each deposit just also has to keep track of the unlock time. In the withdraw method you just need an additional check to make sure that the unlock time is lower than the current block timestamp.

What happens if a user deposits more than once, are they extending the lock on the full balance? Are they setting a new (lower multiple) given the remaining time on the lock? 

From a user perspective if we add time lock multipliers what they would see is:

1. They can deposit liquidity without locks for a base reward (1x)
2. They can deposit liquidity with a lock for a specific duration and receive an addition multiplier based on the lock time (there would be a max lock time and max lock multiplier)
3. Rewards are distributed proportionally to users based on the deposited LP tokens * pool allocation points * reward multiplier
4. If a user chooses to deposit additional LPs they will reset their reward multiplier based on the lock amount they chose, which will be applied to their total deposit balance for that Pool?

One other mechanic we could consider is a Referral bonus, essentially when a user deposits the frontend can pass a referrer address, that will get a bonus allocation. This would provide a way for people to earn rewards for promoting or integrating the farm into their wallet.

**Comment by Philogy** [comment]
Each deposit would have to be tracked separately

**Comment by Blazarius120** [comment]
Remaining questions:
length of time for the farming contracts
the decay rate for farming rewards 
what % will go to farmers vs. referrals

**Comment by lkngtn** [comment]
For the test deployment (and a starting point for discussion)

Length of time for farming contracts = 2 years
99% to farmers, 1% referrals 

I'm not totally sure what the decay rate is, I was under the impression that the rate was linear throughout the period. If that's not the case, how does the decay rate work and how should the parameter be specified?

Edit: We can use 25% for the decay, this means by the end of the 2 year period the rewards will be 25% of what they were at the beginning.
