### ISSUE TITLE
Token address link goes to a 404 on Blockscout

### ISSUE THREAD

**Issue by anachr0n1sm** [1Hive/honeyswap#3]
Clicked on "trade" under the honey price on 1hive.org
"Token imported" prompt pops up on Honeyswap
Clicked on the token address (View on Blockscout) link
Taken to a 404 on Blockscout
![honey](https://user-images.githubusercontent.com/64047032/94086402-d239fb80-fdd8-11ea-81a2-8b549e2173b6.png)
![blockscout](https://user-images.githubusercontent.com/64047032/94086403-d36b2880-fdd8-11ea-9ca2-793dff0c2d42.png)

**Comment by onbjerg** [comment]
Nice catch! Fixed in https://github.com/1Hive/uniswap-interface/pull/8

**Comment by onbjerg** [comment]
Deployed!
