### ISSUE TITLE
Menu Component

### ISSUE THREAD

**Issue by famole** [1Hive/honeyswap#30]

**Comment by famole** [comment]
This task is completed, needs to be reviewed and merged.
Menu, routes, and site holder: https://github.com/1Hive/tulip-frontend/pull/3
Header and wallet connector redesign: https://github.com/1Hive/tulip-frontend/pull/4

**Comment by Blazarius120** [comment]
Phil and Sandpiper to review code before merging, #3 & #4 pull requests.
