### ISSUE TITLE
Deploy Testnet

### ISSUE THREAD

**Issue by Blazarius120** [1Hive/honeyswap#34]

**Comment by Philogy** [comment]
Contracts have been deployed to testnet:
* xComb token: [0xe26EF0e1890d83e196191822752749a37d7A199f](https://rinkeby.etherscan.io/address/0xe26EF0e1890d83e196191822752749a37d7A199f)
* Farm: [0x087B269605a4a9e4c2C9dFAEc424A9Ad46e4d986](https://rinkeby.etherscan.io/address/0x087B269605a4a9e4c2C9dFAEc424A9Ad46e4d986)
* Referral rewarder: [0xB4252EE3503C39C08DC429B4081Cd0100187a721](https://rinkeby.etherscan.io/address/0xB4252EE3503C39C08DC429B4081Cd0100187a721)
* Airdrop contract: [0x4BeA4ba49063061123aC8A51796F277Cfe2457F4](https://rinkeby.etherscan.io/address/0x4BeA4ba49063061123aC8A51796F277Cfe2457F4)
