### ISSUE TITLE
Create snapshot for airdrop

### ISSUE THREAD

**Issue by Philogy** [1Hive/honeyswap#40]
Create snapshot for airdrop. Airdrops should be distributed proportional to share of pool and length in the pool. Successful task completion should result in well formatted list (json / csv) with the xDai address and the amount to be airdropped.

Airdrop details:
- 5% of total xComb supply
- 10% upfront
- 1 year (365 days) vesting (linear distribution)

**Comment by lkngtn** [comment]
Will use $10K minimum liquidity in pairs, (gets us top 50 pairs by liquidity), and based on blockheight 16Million.
