### ISSUE TITLE
Create interface for claiming vested airdrop

### ISSUE THREAD

**Issue by Philogy** [1Hive/honeyswap#41]
Integrate the ability to release the unlocked vested tokens from the xComb vesting contract.

**Comment by lkngtn** [comment]
Should be done May 5/6

**Comment by famole** [comment]
Finished by: https://github.com/1Hive/tulip-frontend/pull/21
There are a few known issues that I'll create a new task for them.

**Comment by pxbee** [comment]
Things to be done:
- [ ] change unclaimed xcomb and claimed amount for correct values
- [x] balance is not loading
- [x] xcomb & pcomb logo sould be variable depending of the network deployed
