### ISSUE TITLE
Update backend service/bots

### ISSUE THREAD

**Issue by lkngtn** [1Hive/honeyswap#45]
* Farming introduces a mechanism where a function needs to be called to downgrade rewards after time lock expiration, we should write a script to automate this. 
* The Fee Receiver contract also need to be called periodically

**Comment by ceresbzns** [comment]
@crisog @MrClottom Is downgrade bot complete? In progress?

**Comment by Philogy** [comment]
For full disclosure I have created a downgrade bot in private which I run time to time.
