### ISSUE TITLE
Tulip Backend

### ISSUE THREAD

**Issue by pxbee** [1Hive/honeyswap#46]
API which collects data from different sources and makes it easily accessible in the frontend. The MVP contains the following information:

**Wallet**
 - Asset balances for tokens listed on honeyswap
 - Honeyswap pair balances 
 - Honeyfarm staked pair balances

**Farm**
 - info ( about the contract parameters )
 - pools
 - pools with apys
 - deposits

For the rinkeby testing the pools and the xcomb token will be mapped to existing pools on honeyswap to have proper values.

**Comment by pxbee** [comment]
To be done:
- [x] APY calculation 
- [x] Mapping of the rinkeby pools to the pooldata from honeyswap 
- [x] Adapt to new honeyswap subgraph
- [x] Move to 1hive repo

**Comment by famole** [comment]
Could this library be published as a npm package under the npm 1hive org?

**Comment by lkngtn** [comment]
@famole I don't see why it couldn't, cc @crisog
