### ISSUE TITLE
Polygon Deployment

### ISSUE THREAD

**Issue by lkngtn** [1Hive/honeyswap#48]

**Comment by lkngtn** [comment]
- [x] Deploy AMM contracts using WETH as the preferred base pair (half price swaps) on Polygon.
- [ ] Deploy pComb and pComb Farming Contract
- [ ] Deploy Fee Splitter
- [ ] Deploy pComb Airdrop Contract
- [ ] Deploy Tulip Multisig (Aragon) to manage Fees/Rewards parameters

**Comment by willjgriff** [comment]
DXswapFactory / HoneyswapFactory: `0x6F937495013C7DC42aF752d3E0BcC090bd34F7AB`
DXswapRouter / HoneyswapRouter: `0x346880305b57c5A8AaF4170D951f13e91c0bE0a7`

Note I can't deploy the FeeReceiver until we've deployed the farming contract.

**Comment by lkngtn** [comment]
Let's make sure we verify the contracts on Matic's main block explorer https://explorer-mainnet.maticvigil.com/

**Comment by willjgriff** [comment]
Latest deployment.

Factory: https://explorer-mainnet.maticvigil.com/address/0x03DAa61d8007443a6584e3d8f85105096543C19c/contracts
Router: https://explorer-mainnet.maticvigil.com/address/0xaD340d0CD0B117B0140671E7cB39770e7675C848/contracts
