### ISSUE TITLE
New Honeyswap Frontend Deployment

### ISSUE THREAD

**Issue by lkngtn** [1Hive/honeyswap#50]
Forked from Swapr, the new Honeyswap frontend supports connecting from either xDai or Polygon, and will route users to the best trade (for supported AMMs). This way users can be confident they will get the best rate on whatever network they are on by using the Honeyswap interface.

Supported AMMs on Polygon
- Honeyswap
- Quickswap
- Sushi

Supported AMMs on xDai
- Honeyswap
- Swapr
- Baoswap
- Sushi

**Comment by ceresbzns** [comment]
Closing this. Will make a new ticket for Polygon.

**Comment by ghost** [comment]
Awesome work here people.  I am just studying by observation.
