### ISSUE TITLE
Honeycomb Frontend

### ISSUE THREAD

**Issue by Blazarius120** [1Hive/honeyswap#6]
replace hny.farm with new UI based on designs here:
https://www.figma.com/proto/SHx5MhZxSlh1bMWYMmzCZv/Honeycomb-new?node-id=45%3A3431&scaling=min-zoom

We will be working from this repo: https://github.com/1Hive/tulip-frontend

**Comment by Blazarius120** [comment]
1) Farm interface
By using the MasterChef contract we can more easily adapt existing farming frontend work.

-we could fork the baoboard interface
-We could upgrade the honeyswap interface to include the latest upstream changes, including the airdrop claim feature and the farming tab, but we would need to adapt the farming tab more extensively since they were not doing masterchef style farms as I recall.
-we could fork the sushiswap app, but likely a bit more work, but it would be an upgrade to the analytics site at the same time.
-we could do something from scratch, inspired by the farming tab of zapper.fi, which we could then extend into the honeycomb wallet milestone.

**Comment by ceresbzns** [comment]
xDAI farms launched. Closing epic.
