### ISSUE TITLE
info.honeyswap.org shows xdai tokens/pairs even when polygon is selected in dropdown

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#65]
**Describe the bug**
info.honeyswap.org shows xdai tokens/pairs even when polygon is selected in dropdown

**To Reproduce**
1. Go to info.honeyswap.org
2. Click on network selector
3. Select Polygon
3. Wait 10 seconds

**Expected behavior**
Stats show polygon token/pair data

**Actual behavior**
Stats flip from showing polygon data to xdai token/pair data
color theme stays the same, chart at top stays the same

**Screenshots**
![Capture.PNG](https://images.zenhubusercontent.com/60b150d0aa64fc7a662399c6/0fcfa639-4c1e-4ca9-b7ba-6557c9428460)

**Desktop (please complete the following information):**
 - OS: Windows
 - Safari v89
 - Also reproduced in Chrome

**Comment by onbjerg** [comment]
I'm looking into this

For reference this is reproducable in Firefox 88.0.1 on Manjaro too

**Comment by onbjerg** [comment]
While debugging the bug disappeared by itself. Classic case of a Heisenbug. Is this still an issue on your end?

I'm unassigning myself for now, since I can no longer reproduce it.

**Comment by ceresbzns** [comment]
I also haven't been able to reproduce this recently either. Gonna close it for now. Hopefully it stays gone.
