### ISSUE TITLE
[POLYGON] Set up admin multisig for Farming Deployment

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#66]
Decision point: how do we manage governance for rewards distribution on Polygon? 
* Can't use the 1Hive decision b/c it doesn't exist on-chain on Polygon

Tasks to achieve:
1) set up multisig for manager role -> Use Tulip multisig (same as xDAI)
2) set up multisig for governor role 

Luke will drop hackmd link in comments with options.

**Comment by ceresbzns** [comment]
https://hackmd.io/76Cr5bHdQzeXoKs0bsDtCA

**Comment by ceresbzns** [comment]
After reviewing the hackMD, it looks like the approach that will allow us to move fastest with the least risk is to use Proposal 1: Use Aragon

Any objections to this approach?

**Comment by ceresbzns** [comment]
Luke: aiming for Aragon deployment this week **June 18**

**Comment by 0xGabi** [comment]
I set up an Aragon Organization for Tulip Swarm on Polygon. Here it is: https://aragon.1hive.org/#/tulipswarm/

Note you should choose polygon network under settings. If you have issues loading the apps in the Aragon Client you can use our node. You need to update the network settings for: `wss://winter-twilight-firefly.matic.quiknode.pro/`. Once the CNAME configure, you will be able to use `wss://polygon.1hive.org/`.


Agent app address is: `0xdc9260ad6a3a05609e15f57073ed045593309afa`
