### ISSUE TITLE
[POLYGON] Take snapshot of addresses for pCOMB airdrop

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#67]
As a Tulip Swarm member, I would like to have the full list of addresses eligible for pCOMB airdrop and relevant data (e.g., time, amounts), so that I can deploy the airdrop

**Comment by ceresbzns** [comment]
**AIRDROP GROUP ONE**
POLYGON DEFI
Distributions weighted by total liquidity and time held
April 1st — May 21st

QUICKSWAP: 
* 12500 pCOMB 
* top 30 highest liquidity pairs

AAVE
* 2500 pCOMB
* All depositors

SUSHISWAP
* 3333 pCOMB
* LPs in top 7 weth pairs

CURVE
* 3333 pCOMB
* all LPs

DFYN
* 3333 pCOMB
* LPs in top 10 highest liquidity pairs 

**AIRDROP GROUP TWO**
HONEYSWAP POLYGON LPs
* 25000 pCOMB 
Distributions weighted by total liquidity and time held (May 21 - July 1)

**AIRDROP GROUP THREE**
TULIP SWARM DISCRETIONARY AIRDROP
* 50000 pCOMB

**Comment by Monstrosity1** [comment]
quickswap, sushiswap, and dfyn use farms so there will be stakers and no stakers that we need to include

**Comment by Monstrosity1** [comment]
I’m addition to the allocation above:

Distributions weighted by total liquidity and time held (May 21 - July 1)
25,000 to honeyswap LPs on polygon

50,000 to tulip swarm address

The 25,000 to various defi platforms above date range is (April 1 - May 21)

**Comment by ceresbzns** [comment]
@MrClottom Details updated in comment - can you confirm if you need any additional information?
