### ISSUE TITLE
[POLYGON] Announce launch of Honeycomb & Airdrop

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#68]
As a Polygon defi participant, I'd like to be aware of the new Honeycomb farming opportunity, so that I can deploy my capital to get rewards

**Comment by ceresbzns** [comment]
Dosh is taking point on this

**Comment by TheD0SH** [comment]
Written content based on https://hackmd.io/Vt5nbCuXSIqaUbF5ecbNIw?both by - David
Thumbnail - Harsh24
Additional timeline image- Twells

Announcement takes place as soon as all 3 are ready and reviewed, followed by our network to help us out
