### ISSUE TITLE
Sustainable Farming

### ISSUE THREAD

**Issue by lkngtn** [1Hive/honeyswap#7]
Honeycomb and related functionality

**Comment by Blazarius120** [comment]
Scope
1) deploy the HSF-xDai token
2) airdrop to honeyswap LPs (vesting party?)
3) fee router (replace honeymaker)
4) farm contract (replace unipool factory)
5) farm frontend (replace hny.farm)

**Comment by ceresbzns** [comment]
Farms are launched on xDai - closing the epic.
