### ISSUE TITLE
[POLYGON] Optimize router logic

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#77]
## User story

As a swapper on Honeyswap Polygon, I want to get the most efficient swap path possible, so that I am getting the most token for my token. 

## Acceptance Criteria

GIVEN I am on Honeyswap Polygon
WHEN I pick two tokens to swap that have a common wETH-pair
THEN I receive the most efficient swap available

## Notes
* Crucial for delivering cost-effective swaps for traders who give us the volume we need to generate value for 1Hive

**Comment by mrtdlgc** [comment]
here are the examples. it is supposed to route through eth-hny pair. and i'm uploading two screenshots to show that it is not actually related to the amount of the swap.
![image.png](https://images.zenhubusercontent.com/60ba5dce3260a12ff48905d0/09f05cc1-56c8-4337-a90d-e6cf65e1072e)

![image.png](https://images.zenhubusercontent.com/60ba5dce3260a12ff48905d0/51bc9b4c-0961-4741-ba59-f3c3186bbc76)

**Comment by mrtdlgc** [comment]
Just an idea by the way, the router may not be able to route through ETH pairs. As in the following example, it should typically route through wmatic-weth-wbtc; but it cannot find the route through ETH.

![image.png](https://images.zenhubusercontent.com/60ba5dce3260a12ff48905d0/11e12f6f-9bc0-458a-94ac-8b0e32ebe854)

**Comment by onbjerg** [comment]
Looked into it with @lkngtn and the WETH address on Polygon was wrong, otherwise everything seems fine: https://github.com/1Hive/honeyswap-sdk/pull/7

**Comment by onbjerg** [comment]
Fixed in https://github.com/1Hive/honeyswap-sdk/pull/7 and https://github.com/1Hive/honeyswap-interface/pull/50
