### ISSUE TITLE
[POLYGON] Switch blockchain explorer links to PolygonScan

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#90]
## User story

As a Honeyswap user, I would like blockchain explorer links to send to PolygonScan, so that I can see transactions and accounts on the support explorer

## Acceptance Criteria

GIVEN I am on the Honeyswap charts page
AND I have selected the Polygon network from the dropdown
WHEN I click an account
THEN I am connected to the account page on PolygonScan explorer

GIVEN I am on the Honeyswap charts page
AND I have selected the Polygon network from the dropdown
WHEN I click a transaction 
THEN I am connected to the transaction page on PolygonScan explorer

## Notes
* MaticVigil is being deprecated and replaced by PolygonScan.com

**Comment by onbjerg** [comment]
See https://github.com/1Hive/honeyswap-info/pull/13
