### ISSUE TITLE
Add Certik Audit to wiki and link on frontend

### ISSUE THREAD

**Issue by ceresbzns** [1Hive/honeyswap#94]
As a DeFi degen, I want to know that the Honeyswap contracts have been audited, so that I can yeet my fortunes without worrying I'm gonna get rugpulled.

TODO: 
* Add a link to the wiki entry on the 1hive.io page

**Comment by ceresbzns** [comment]
From Phil:
"some changes have been made to the contracts post audit. Despite this the core mechanisms remain unchanged thus the audit still provides a valid assessment of the current state of the security of the main contracts."

There should also be a notice explaining that the airdrop contract hasn't been audited but that it's ok because it's a very simple contract and it only holds the airdrop funds, it does not interact or influence the farm contracts in any way

**Comment by ceresbzns** [comment]
Wiki entry: https://wiki.1hive.org/projects/honeyswap/audits-and-security

**Comment by borisblock3007** [comment]
the simplest way to add audit link is footer section, below forum and github links, like so:
![footer.png](https://images.zenhubusercontent.com/600ff0db06c4d172252b3461/2374cefc-840c-496f-aad4-60315ead2f55)
https://www.figma.com/file/SHx5MhZxSlh1bMWYMmzCZv/Honeycomb-new?node-id=1143%3A1326

**Comment by ceresbzns** [comment]
Can we change the hyperlink text to `Audited by Certik` please?
