### ISSUE TITLE
add a network switch button for mobile on the analytics page

### ISSUE THREAD

**Issue by Blazarius120** [1Hive/honeyswap#98]
As a mobile user on the Honeyswap charts site, I'd like to be able to switch between viewing Polygon and xDai data, so that I can look up Honeyswap data on Polygon without having to be at a desktop.

Notably, switching to desktop mode on the mobile browser still doesn't present the button.

**Comment by Harthor** [comment]
https://github.com/1Hive/honeyswap-info/pull/16
